dormy/urls.py
from django.conf.urls import patterns, include, url
from dormy.views import landing, home

#The following is for Dajaxice - Kerrod
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()
from django.contrib.staticfiles.urls import staticfiles_urlpatterns




# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'webapp.views.home', name='home'),
    # url(r'^webapp/', include('webapp.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),i

    # Basic Urls
    url(r'^$', landing),
    url(r'^home/$', home),


    # Landing Urls
    url(r'^login/$', 'dormy.views.login'),
 #   url(r'^accounts/auth/$', 'dormy.views.auth_view'),
    url(r'^accounts/login/$', 'dormy.views.login'),
    url(r'^accounts/logout/$', 'dormy.views.logout'),
    url(r'^accounts/loggedin/$', 'dormy.views.loggedin'),
    url(r'^accounts/invalid/$',	'dormy.views.invalid_login'),
 #   url(r'^accounts/register/$', 'users.views.register'),
    url(r'^register/$', 'users.views.register'),
    url(r'^firstTimeUser/$', 'dormy.views.firstTime'),
    url(r'^accounts/register/register_success/$', 'dormy.views.register_success'),


    # Club Urls
    url(r'^clubs/$', 'dormy.views.clubs'),
    url(r'^clubs/(?P<socCode>\w{0,10})/$', 'dormy.views.club_page'),
    url(r'^clubs/find=(?P<phrase>\w{0,30})', 'societies.views.search'),

    # Calendar Urls
    url(r'^cal/$', 'dormy.views.cal'),

    # Profile Urls
    url(r'^profile/(?P<userN>\w{0,20})/$', 'dormy.views.profile_page'),

    url(r'^profile/find$', 'users.views.searchUsers'),

    # Admin Urls
    url(r'^admin/$', 'dormy.views.admin'),



    # Dajaxice Urls - Kerrod
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
)


urlpatterns += staticfiles_urlpatterns()

societies/models.py
from django.db import models
from users.models import Students
from time import time

def get_upload_file_name(instance, filename):
	return "club_pics/%s_%s" % (str(time()). replace('.','_'), filename)


# Create your models here.
class Societies(models.Model):
	NAME = models.CharField(max_length=30)
	DESCR = models.CharField(max_length=200)
	OWNER = models.ForeignKey(Students)
	CODE = models.CharField(max_length=8)
	# Not actually needed for this implementation. Should probably change since it has 
	# usyd only application
	USU = models.CharField(max_length=10, blank=True)
	UPG = models.BooleanField()
	IMG = models.ImageField(upload_to=get_upload_file_name, blank=True)

	def __unicode__(self):
		return u'%s %s' % (self.NAME, self.OWNER)


class Stu_Soc(models.Model):
	SOC_ID = models.ForeignKey(Societies)
	STU_ID = models.ForeignKey(Students)
	TIME = models.DateTimeField(auto_now_add=True)
	ROLE = models.CharField(max_length=50)

	def __unicode__(self):
		return u'%s %s %s' % (self.SOC_ID, self.STU_ID, self.TIME)

class Events(models.Model):
	SOC_ID = models.ForeignKey(Societies)
	NAME = models.CharField(max_length=30)
	DESCR = models.CharField(max_length=200)
	TIME = models.DateField(max_length=40)


	def __unicode__(self):
		return u'%s %s' % (self.SOC_ID, self.DESCR)



class Posts(models.Model):
	SOC_ID = models.ForeignKey(Societies)
	CONTENT = models.CharField(max_length=200)
	TIME = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return u'%s %s' % (self.SOC_ID, self.CONTENT)

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Students(models.Model):
	user = models.OneToOneField(User)
	F_NAME = models.CharField(max_length=30)
	L_NAME = models.CharField(max_length=30)
	DEGREE = models.CharField(max_length=50)
	# Isn't used but needed for forms
	EMAIL = models.EmailField(max_length=75)

	def __unicode__(self):
		return u'%s %s' % (self.F_NAME, self.L_NAME)

User.student = property(lambda u: Students.objects.get_or_create(user=u) [0])

class Achieves(models.Model):
	ACH_NAME = models.CharField(max_length=30)
	DESCR = models.CharField(max_length=100)
	ACH_POINTS = models.CharField(max_length=4)

	def __unicode__(self):
		return u'%s %s' % (self.ACH_NAME, self.DESCR)


class Stu_Ach(models.Model):
	ACH_ID = models.ForeignKey(Achieves)
	STU_ID = models.ForeignKey(Students)
	TIME = models.DateTimeField(auto_now_add=True)

	def __unicode__(self): 
		return u'%s %s %s' % (self.ACH_ID, self.STU_ID, self.TIME)


# Admins are an offshoot of Users, manually created through the database,
# I.e. Admins cannot be created through the website itself, as a security measure.

templates/Clubs/clubPage.html
{% extends "Base/base.html" %}


{% block title %}Dormy - {{ soc.CODE }} {% endblock %}


{% block head %}


<style>
input#id_CONTENT{
		border:0px;
		box-shadow: 0px 0px 0px 1px rgba(0,0,0,0.3);
		width: 140px;
		height: 30px;
		/*margin-left: 13%;*/
		background: -moz-linear-gradient(top,  rgba(245, 245, 245,1) 0%, rgba(245, 245, 245,0) 100%); /* FF3.6+ */
		background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(245, 245, 245,1)), color-stop(100%,rgba(245, 245, 245,0))); /* Chrome,Safari4+ */
		background: -webkit-linear-gradient(top,  rgba(245, 245, 245,1) 0%,rgba(245, 245, 245,0) 100%); /* Chrome10+,Safari5.1+ */
		background: -o-linear-gradient(top,  rgba(245, 245, 245,1) 0%,rgba(245, 245, 245,0) 100%); /* Opera 11.10+ */
		background: -ms-linear-gradient(top,  rgba(245, 245, 245,1) 0%,rgba(245, 245, 245,0) 100%); /* IE10+ */
		background: linear-gradient(to bottom,  rgba(245, 245, 245,1) 0%,rgba(245, 245, 245,0) 100%); /* W3C */
		filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#00ffffff',GradientType=0 ); /* IE6-9 */
	}

	.posts {
		-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
		-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
		box-shadow:inset 0px 1px 0px 0px #ffffff;
		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #f9f9f9), color-stop(1, #e9e9e9) );
		background:-moz-linear-gradient( center top, #f9f9f9 5%, #e9e9e9 100% );
		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#f9f9f9', endColorstr='#e9e9e9');
		background-color:#f9f9f9;
		-webkit-border-top-left-radius:20px;
		-moz-border-radius-topleft:20px;
		border-top-left-radius:20px;
		-webkit-border-top-right-radius:20px;
		-moz-border-radius-topright:20px;
		border-top-right-radius:20px;
		-webkit-border-bottom-right-radius:20px;
		-moz-border-radius-bottomright:20px;
		border-bottom-right-radius:20px;
		-webkit-border-bottom-left-radius:20px;
		-moz-border-radius-bottomleft:20px;
		border-bottom-left-radius:20px;
		text-indent:0;
		border:1px solid #dcdcdc;
		display:inline-block;
		color:#666666;
		font-family:wind;
		font-size:15px;
		font-weight:bold;
		font-style:normal;
		height:35px;
		line-height:35px;
		width:93px;
		text-decoration:none;
		text-align:center;
		text-shadow:1px 1px 0px #ffffff;
		margin-left: 30%;
	}
	.posts:hover {
		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #e9e9e9), color-stop(1, #f9f9f9) );
		background:-moz-linear-gradient( center top, #e9e9e9 5%, #f9f9f9 100% );
		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#e9e9e9', endColorstr='#f9f9f9');
		background-color:#e9e9e9;
	}
	.posts:active {
		position:relative;
		top:1px;
	}
	
	.updateBox{
		position: relative;
		width:50%;
		min-height: 60px;
		padding:30px;
		border: 0px;
		margin-left:2%;
		margin-bottom: 10px;
		background-image: url({{ STATIC_URL }}images/feedBack.png); 
		-webkit-background-size: cover;
		-moz-background-size: cover;
		-o-background-size: cover;
		background-size: cover;		
		border-color: 000000;
		background-color: #ffffff;
		border-radius: 5px;
		-moz-box-shadow:1px 1px 2px rgba(0,0,0,.5);
		-webkit-box-shadow:1px 1px 5px rgba(0,0,0,.5);
		box-shadow: 1px 1px 2px rgba(0,0,0,.5);
	}

	.updateimage {
		float: left;
		padding-right: 10px;
		padding-bottom: 10px;
	}

	#timestamp {
		position: absolute;
		right: 10px;
		bottom: 0px;
		opacity: 0.6;
	}
</style>

{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-3">
		{% if soc.IMG %}
			<img src="{{ STATIC_URL }}{{ soc.IMG }}" class="img-rounded" width='200' height='200'>
		{% else %}
			<img src="http://placehold.it/200x200" class="img-rounded">
		{% endif %}
	</div>
		<div class="col-md-6">
		<h1>{{soc.NAME}}</h1>
		<h3>{{soc.CODE}}</h3>
		{% if soc.UPG %}
			<h3><img src="{{ STATIC_URL }}icon_society.png" class="img-rounded" width='160' height='100'></h3>
		{% else %}
			<img src="{{ STATIC_URL }}icon_club.png" class="img-rounded" width='160' height='100'>
		{% endif %}
		<button onclick="location.href='/profile/{{ owner }}'" class="btn btn-info">Club Leader: {{ soc.OWNER }}</button>
		<h5>{{soc.DESCR}}</h5>
	</div>
	<div class="col-md-3">
			<button id="followClub" class="btn btn-primary button" type="button" onclick="Dajaxice.societies.dajaxice_example(follow, {'soc': '{{ soc.id }}', 'user': '{{ user.id }}'})" >Follow</button>
			<br>
			<span>There are</span> 
			<h2>{{followers}}</h2>
			<span> Students following this Club!</span>
	</div>
</div>
<div>
	<h2> Activity</h2>
	<div id="container">
		{% for up in updates %}
		<div class="updateBox feedItem">
			<div class="updateimage">
				{% if up.SOC_ID.IMG %}
				<img src="{{ STATIC_URL }}{{ up.SOC_ID.IMG }}" class="img-rounded" width='50' height='50' onclick="location.href='/clubs/{{up.SOC_ID.CODE}}'" >
				{% else %}
				<img src="http://placehold.it/50x50" class="img-rounded" onclick="location.href='/clubs/{{up.SOC_ID.CODE}}'">
				{% endif %}
			</div>    	
			<p> {{up.SOC_ID.NAME}}</p>
			<p> {{up.CONTENT}}</p>
			<div id="timestamp">
				<p> {{up.TIME}}</p>
			</div>
		</div>
		{% endfor %}
	</div>

</div>

<script>
	$(document).ready(function(){

		if("{{follow}}" == "True") {
			$("#followClub").addClass("btn-success")
			$("#followClub").removeClass("btn-primary")
			$("#followClub").html("Following")
		}
		else {
			// Leave it as is...
		}
		$('#container').isotope({
			itemSelector: '.feedItem',
			layoutMode: 'masonry'

		});


		$( "#followClub" )
		  .mouseenter(function() {
  			if("{{follow}}" == "True") {
				$("#followClub").addClass("btn-danger")
				$("#followClub").removeClass("btn-success")
				$("#followClub").html("Unfollow")
			}			      
		  })
		  .mouseleave(function() {
  			if("{{follow}}" == "True") {
				$("#followClub").addClass("btn-success")
				$("#followClub").removeClass("btn-danger")
				$("#followClub").html("Following")
			}	
		});
	});


	function follow(data){
		alert(data.message);
		location.reload();
	}
</script>

{% endblock %}

templates/Clubs/clubPage_owner.html
{% extends "Base/base.html" %}

{% block title %}Dormy - {{ soc.CODE }} {% endblock %}

{% block head %}

<style>
input#id_CONTENT{
		border:0px;
		box-shadow: 0px 0px 0px 1px rgba(0,0,0,0.3);
		width: 140px;
		height: 30px;
		/*margin-left: 13%;*/
		background: -moz-linear-gradient(top,  rgba(245, 245, 245,1) 0%, rgba(245, 245, 245,0) 100%); /* FF3.6+ */
		background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(245, 245, 245,1)), color-stop(100%,rgba(245, 245, 245,0))); /* Chrome,Safari4+ */
		background: -webkit-linear-gradient(top,  rgba(245, 245, 245,1) 0%,rgba(245, 245, 245,0) 100%); /* Chrome10+,Safari5.1+ */
		background: -o-linear-gradient(top,  rgba(245, 245, 245,1) 0%,rgba(245, 245, 245,0) 100%); /* Opera 11.10+ */
		background: -ms-linear-gradient(top,  rgba(245, 245, 245,1) 0%,rgba(245, 245, 245,0) 100%); /* IE10+ */
		background: linear-gradient(to bottom,  rgba(245, 245, 245,1) 0%,rgba(245, 245, 245,0) 100%); /* W3C */
		filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#00ffffff',GradientType=0 ); /* IE6-9 */
	}

	.posts {
		-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
		-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
		box-shadow:inset 0px 1px 0px 0px #ffffff;
		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #f9f9f9), color-stop(1, #e9e9e9) );
		background:-moz-linear-gradient( center top, #f9f9f9 5%, #e9e9e9 100% );
		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#f9f9f9', endColorstr='#e9e9e9');
		background-color:#f9f9f9;
		-webkit-border-top-left-radius:20px;
		-moz-border-radius-topleft:20px;
		border-top-left-radius:20px;
		-webkit-border-top-right-radius:20px;
		-moz-border-radius-topright:20px;
		border-top-right-radius:20px;
		-webkit-border-bottom-right-radius:20px;
		-moz-border-radius-bottomright:20px;
		border-bottom-right-radius:20px;
		-webkit-border-bottom-left-radius:20px;
		-moz-border-radius-bottomleft:20px;
		border-bottom-left-radius:20px;
		text-indent:0;
		border:1px solid #dcdcdc;
		display:inline-block;
		color:#666666;
		font-family:wind;
		font-size:15px;
		font-weight:bold;
		font-style:normal;
		height:35px;
		line-height:35px;
		width:93px;
		text-decoration:none;
		text-align:center;
		text-shadow:1px 1px 0px #ffffff;
		margin-left: 30%;
	}
	.posts:hover {
		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #e9e9e9), color-stop(1, #f9f9f9) );
		background:-moz-linear-gradient( center top, #e9e9e9 5%, #f9f9f9 100% );
		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#e9e9e9', endColorstr='#f9f9f9');
		background-color:#e9e9e9;
	}
	.posts:active {
		position:relative;
		top:1px;
	}
	
	.updateBox{
		position: relative;
		width:50%;
		min-height: 60px;
		padding:30px;
		border: 0px;
		margin-left:2%;
		margin-bottom: 10px;
		background-image: url({{ STATIC_URL }}images/feedBack.png); 
		-webkit-background-size: cover;
		-moz-background-size: cover;
		-o-background-size: cover;
		background-size: cover;		
		border-color: 000000;
		background-color: #ffffff;
		border-radius: 5px;
		-moz-box-shadow:1px 1px 2px rgba(0,0,0,.5);
		-webkit-box-shadow:1px 1px 5px rgba(0,0,0,.5);
		box-shadow: 1px 1px 2px rgba(0,0,0,.5);
	}

	.updateimage {
		float: left;
		padding-right: 10px;
		padding-bottom: 10px;
	}

	#timestamp {
		position: absolute;
		right: 10px;
		bottom: 0px;
		opacity: 0.6;
	}

	.submitting {
		-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
		-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
		box-shadow:inset 0px 1px 0px 0px #ffffff;
		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #f9f9f9), color-stop(1, #e9e9e9) );
		background:-moz-linear-gradient( center top, #f9f9f9 5%, #e9e9e9 100% );
		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#f9f9f9', endColorstr='#e9e9e9');
		background-color:#f9f9f9;
		-webkit-border-top-left-radius:20px;
		-moz-border-radius-topleft:20px;
		border-top-left-radius:20px;
		-webkit-border-top-right-radius:20px;
		-moz-border-radius-topright:20px;
		border-top-right-radius:20px;
		-webkit-border-bottom-right-radius:20px;
		-moz-border-radius-bottomright:20px;
		border-bottom-right-radius:20px;
		-webkit-border-bottom-left-radius:20px;
		-moz-border-radius-bottomleft:20px;
		border-bottom-left-radius:20px;
		text-indent:0;
		border:1px solid #dcdcdc;
		display:inline-block;
		color:#666666;
		font-family:wind;
		font-size:15px;
		font-weight:bold;
		font-style:normal;
		height:35px;
		line-height:35px;
		width:93px;
		text-decoration:none;
		text-align:center;
		text-shadow:1px 1px 0px #ffffff;
		margin-left: 30%;
	}
	.submitting:hover {
		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #e9e9e9), color-stop(1, #f9f9f9) );
		background:-moz-linear-gradient( center top, #e9e9e9 5%, #f9f9f9 100% );
		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#e9e9e9', endColorstr='#f9f9f9');
		background-color:#e9e9e9;
	}
	.submitting:active {
		position:relative;
		top:1px;
	}

</style>

{% endblock %}

{% block content %}

<div class="row">
	<div class="col-md-3">
		{% if soc.IMG %}
			<img src="{{ STATIC_URL }}{{ soc.IMG }}" class="img-rounded" width='200' height='200'>
		{% else %}
			<img src="http://placehold.it/200x200" class="img-rounded">
		{% endif %}
	</div>
	<div class="col-md-6">
		<h1>{{soc.NAME}}</h1>
		<h3>{{soc.CODE}}</h3>
		{% if soc.UPG %}
			<h3><img src="{{ STATIC_URL }}icon_society.png" class="img-rounded" width='160' height='100'></h3>
		{% else %}
			<img src="{{ STATIC_URL }}icon_club.png" class="img-rounded" width='160' height='100'>
		{% endif %}
		<button onclick="location.href='/home'" class="btn btn-info">Club Leader: {{ user.username }}</button>
		<h5>{{soc.DESCR}}</h5>
	</div>
	<div class="col-md-3">
			<button id="edit" class="btn btn-primary button" type="button" data-toggle="tooltip" data-trigger="click" data-placement="auto" data-html="True">
				Edit Club</button>
			<div id="edit-head" class="hide">Edit {{soc.CODE}}</div>
			<div id="edit-content" class="hide">
				<form method='post' action='.' enctype="multipart/form-data"> {% csrf_token %}
			       <!-- display the form fields -->
			       {{ editF }}
			       <!-- submit button -->
			       <input type="submit" class="submitting" name="edit" value="Save Changes">
			   </form>
			</div>
			<br>
			<br>
			<span>There are</span> 
			<h1>{{followers}}</h1>
			<span> Students following this Club!</span>
			<br>
			<button class="btn btn-danger delete" type="button">Delete Club</button>
	</div>
		
</div>
<br>
<p align="centre">{{error}}</p>
<div class="row">
	<div class="col-md-6">
		<button id="post" type="button" class="btn btn-success button" data-toggle="tooltip" data-trigger="click" data-placement="bottom" data-html="True">
		Create Post</button>
	</div>
	<div class="col-md-6">
		<button id="events" type="button" class="btn btn-success button" data-toggle="tooltip"
		data-trigger="click" data-placement="bottom" data-html="True">
		Create Event</button>
	</div>
</div>

<div id="events-head" class="hide">Create New Event</div>
<div id="events-content" class="hide">
	<form method='post' action='.'> {% csrf_token %}
       <!-- display the form fields -->

       {{ eventsF.non_field_errors }}

			<div class="fieldWrapper">
				{{ eventsF.NAME.errors }}
				<label for="id_sender">EVENT NAME: </label><br>
				{{ eventsF.NAME}}
			</div>

			<div class="fieldWrapper">
				{{ eventsF.DESCR.errors }}
				<label for="id_sender">EVENT DESCRIPTION: </label><br>
				{{ eventsF.DESCR}}
			</div>

			<div class="fieldWrapper">
				{{ eventsF.TIME.errors }}
				<label for="id_sender">EVENT DATE: </label>
				{{ eventsF.TIME}}
			</div>
			(e.g. YYYY-MM-DD)


       <!-- submit button -->
       <input class="submitting" type="submit" name="events" value="Create Event">
   </form>
</div>

<div id="post-head" class="hide">Create New Post</div>
<div id="post-content" class="hide">
	<form method='post' action='.'> {% csrf_token %}
       <!-- display the form fields -->
       {{ postsF }}

       <!-- submit button -->
       <input class="submitting" type="submit" value="Post" name="posts">	
</div>

<div>
	<h2> Activity</h2>
	<div id="container">
		{% for up in updates %}
		<div class="updateBox feedItem">
			<div class="updateimage">
				{% if up.SOC_ID.IMG %}
				<img src="{{ STATIC_URL }}{{ up.SOC_ID.IMG }}" class="img-rounded" width='50' height='50' onclick="location.href='/clubs/{{up.SOC_ID.CODE}}'">
				{% else %}
				<img src="http://placehold.it/50x50" class="img-rounded" onclick="location.href='/clubs/{{up.SOC_ID.CODE}}'">
				{% endif %}
			</div>
			<p> {{up.SOC_ID.NAME}}</p>
			<p> {{up.CONTENT}}</p>
			<div id="timestamp">
				<p> {{up.TIME}}</p>
			</div>
		</div>
		{% endfor %}
	</div>

</div>

<style>

	#id_CONTENT,
	#id_TIME,
	#id_DESCR,
	#id_NAME{
		border:0px;
		box-shadow: 0px 0px 0px 1px rgba(0,0,0,0.3);
		width: 80%;
		height: 30px;
		margin-left: 10%;
		background: -moz-linear-gradient(top,  rgba(245, 245, 245,1) 0%, rgba(245, 245, 245,0) 100%); /* FF3.6+ */
		background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(245, 245, 245,1)), color-stop(100%,rgba(245, 245, 245,0))); /* Chrome,Safari4+ */
		background: -webkit-linear-gradient(top,  rgba(245, 245, 245,1) 0%,rgba(245, 245, 245,0) 100%); /* Chrome10+,Safari5.1+ */
		background: -o-linear-gradient(top,  rgba(245, 245, 245,1) 0%,rgba(245, 245, 245,0) 100%); /* Opera 11.10+ */
		background: -ms-linear-gradient(top,  rgba(245, 245, 245,1) 0%,rgba(245, 245, 245,0) 100%); /* IE10+ */
		background: linear-gradient(to bottom,  rgba(245, 245, 245,1) 0%,rgba(245, 245, 245,0) 100%); /* W3C */
		filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#00ffffff',GradientType=0 ); /* IE6-9 */
	}

	.submitting {
		-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
		-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
		box-shadow:inset 0px 1px 0px 0px #ffffff;
		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #f9f9f9), color-stop(1, #e9e9e9) );
		background:-moz-linear-gradient( center top, #f9f9f9 5%, #e9e9e9 100% );
		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#f9f9f9', endColorstr='#e9e9e9');
		background-color:#f9f9f9;
		-webkit-border-top-left-radius:20px;
		-moz-border-radius-topleft:20px;
		border-top-left-radius:20px;
		-webkit-border-top-right-radius:20px;
		-moz-border-radius-topright:20px;
		border-top-right-radius:20px;
		-webkit-border-bottom-right-radius:20px;
		-moz-border-radius-bottomright:20px;
		border-bottom-right-radius:20px;
		-webkit-border-bottom-left-radius:20px;
		-moz-border-radius-bottomleft:20px;
		border-bottom-left-radius:20px;
		text-indent:0;
		border:1px solid #dcdcdc;
		display:inline-block;
		color:#666666;
		font-family:wind;
		font-size:15px;
		font-weight:bold;
		font-style:normal;
		height:35px;
		line-height:35px;
		width:93px;
		text-decoration:none;
		text-align:center;
		text-shadow:1px 1px 0px #ffffff;
		margin-left: 30%;
		margin-top: 4px;
	}
	.submitting:hover {
		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #e9e9e9), color-stop(1, #f9f9f9) );
		background:-moz-linear-gradient( center top, #e9e9e9 5%, #f9f9f9 100% );
		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#e9e9e9', endColorstr='#f9f9f9');
		background-color:#e9e9e9;
	}
	.submitting:active {
		position:relative;
		top:1px;
	}

</style>



<script type="text/javascript">

	$('#events').popover({ 
    html : true,
    title: function() {
      return $("#events-head").html();
    },
    content: function() {
      return $("#events-content").html();
    }
	});

	$('#post').popover({ 
    html : true,
    title: function() {
      return $("#post-head").html();
    },
    content: function() {
      return $("#post-content").html();
    }
	});

	$('#edit').popover({ 
    html : true,
    title: function() {
      return $("#edit-head").html();
    },
    content: function() {
      return $("#edit-content").html();
    }
	});


	$( document ).ready(function() {

    	$(".delete").click(function() {
	  		if (confirm("Are you sure? This decision cannot be reversed.")) {
	  			Dajaxice.societies.deleteSoc(deleted, {'soc': '{{ soc.id }}'})
	  		}
	  		return false;
		});
	});

	function deleted(data){
		alert(data.message);
		location.reload();
	}

	$("#container").isotope({
		itemSelector: '.feedItem',
		layoutMode: 'masonry'

	});

</script>

{% endblock %}